save('voCaseComp_refstep_sqrt2.mat','x_I','y_I','z_I','roll','pitch','yaw',...
    'x_I_IB','y_I_IB','z_I_IB','roll_IB','pitch_IB','yaw_IB','x_I_ISM',...
    'y_I_ISM','z_I_ISM','roll_ISM','pitch_ISM','yaw_ISM',...
    'K_P_D','K_P_I','K_P_P','K_R_D','K_R_I','K_R_P',...
    'K_P_1','K_P_2','K_P_3','K_R_1','K_R_2','K_R_3',...
    'lambda','eta','M','lambda_rot','eta_rot','M_rot')